package com.zhang.myspring.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaYear<M extends BaseTaYear<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setYear(java.lang.Integer year) {
		set("year", year);
		return (M)this;
	}
	
	public java.lang.Integer getYear() {
		return getInt("year");
	}

	public M setDynastyId(java.lang.Integer dynastyId) {
		set("dynasty_id", dynastyId);
		return (M)this;
	}
	
	public java.lang.Integer getDynastyId() {
		return getInt("dynasty_id");
	}

}
