package com.zhang.myspring.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaDynasty<M extends BaseTaDynasty<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setBeginYear(java.lang.Integer beginYear) {
		set("begin_year", beginYear);
		return (M)this;
	}
	
	public java.lang.Integer getBeginYear() {
		return getInt("begin_year");
	}

	public M setEndYear(java.lang.Integer endYear) {
		set("end_year", endYear);
		return (M)this;
	}
	
	public java.lang.Integer getEndYear() {
		return getInt("end_year");
	}

	public M setIsAssured(java.lang.Long isAssured) {
		set("is_assured", isAssured);
		return (M)this;
	}
	
	public java.lang.Long getIsAssured() {
		return getLong("is_assured");
	}

	public M setCaptitalId(java.lang.Integer captitalId) {
		set("captital_id", captitalId);
		return (M)this;
	}
	
	public java.lang.Integer getCaptitalId() {
		return getInt("captital_id");
	}

	public M setEmperorId(java.lang.Integer emperorId) {
		set("emperor_id", emperorId);
		return (M)this;
	}
	
	public java.lang.Integer getEmperorId() {
		return getInt("emperor_id");
	}

	public M setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
		return (M)this;
	}
	
	public java.lang.Integer getParentId() {
		return getInt("parent_id");
	}

	public M setLevel(java.lang.Integer level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.Integer getLevel() {
		return getInt("level");
	}

}
