package com.zhang.myspring.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_sys_res", "id", SysRes.class);
		arp.addMapping("t_sys_role", "id", SysRole.class);
		arp.addMapping("t_sys_role_res", "id", SysRoleRes.class);
		arp.addMapping("t_sys_user", "id", SysUser.class);
		arp.addMapping("t_sys_user_role", "id", SysUserRole.class);
		arp.addMapping("t_ta_capital", "id", TaCapital.class);
		arp.addMapping("t_ta_dynasty", "id", TaDynasty.class);
		arp.addMapping("t_ta_emperor", "id", TaEmperor.class);
		arp.addMapping("t_ta_year", "id", TaYear.class);
	}
}

