package com.zhang.myspring.model;

import com.zhang.myspring.model.base.BaseSysRoleRes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleRes extends BaseSysRoleRes<SysRoleRes> {
	public static final SysRoleRes dao = new SysRoleRes().dao();
}
