package com.zhang.myspring.model;

import com.zhang.myspring.model.base.BaseSysRes;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRes extends BaseSysRes<SysRes> {
	public static final SysRes dao = new SysRes().dao();
}
