package com.zhang.myspring.model;

import com.zhang.myspring.model.base.BaseTaCapital;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaCapital extends BaseTaCapital<TaCapital> {
	public static final TaCapital dao = new TaCapital().dao();
}
