package com.zhang.myspring.model;

import com.zhang.myspring.model.base.BaseTaDynasty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaDynasty extends BaseTaDynasty<TaDynasty> {
	public static final TaDynasty dao = new TaDynasty().dao();
}
