package com.zhang.myspring.model;

import com.zhang.myspring.model.base.BaseTaEmperor;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaEmperor extends BaseTaEmperor<TaEmperor> {
	public static final TaEmperor dao = new TaEmperor().dao();
}
