package com.zhang.myspring.model;

import com.zhang.myspring.model.base.BaseTaYear;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TaYear extends BaseTaYear<TaYear> {
	public static final TaYear dao = new TaYear().dao();
}
